### PR TITLE
[WIP] fix: make RCNN detection parameters configurable for better performance

### LINKED ISSUE #266: rcnn object detection head suffer performance issue
rcnn head is far too slow for many potential reason

- [ ] missing configurable confidence threshold (currently[ fixed at 0.05](https://github.com/mlverse/torchvision/blob/64b72849a17af585f47e0a609a0e29ddb4ddf274/R/models-faster_rcnn.R#L410) ) provides too many proposal
- [ ] missing nms_threshold provides too many overlapping bboxes
- [ ] missing max detection per image provides too large tensor output to manage down the line.
- [ ] relying on R-based NMS where `torchvisionlib::ops_nms` provides a torch native implementation

- many more

### PR DESCRIPTION
**Pull request by ANAMASGARD**
FIXES #266 

## Problem

The RCNN object detection models have several performance issues:

1. **Hardcoded 0.05 confidence threshold** - appears at lines 157, 410, 566, 693
   - This is too low and causes many low-confidence detections
   - Should be configurable parameter (PyTorch default: 0.05, recommended: 0.5)

2. **Missing configurable parameters**:
   - No `score_thresh` parameter to filter low-confidence detections
   - No `nms_thresh` parameter for NMS overlap threshold (currently hardcoded at 0.7)
   - No `detections_per_img` parameter to limit maximum detections per image

3. **NMS only used in RPN** (line 162)
   - Final detection postprocessing doesn't apply NMS
   - Causes overlapping detections in output

4. **R-based NMS instead of GPU-accelerated version**
   - Using `nms()` (O(n²) R implementation) 
   - Should use `torchvisionlib::ops_nms` for better performance

## What I Done

✅ Created comprehensive test file using TDD approach
- 7 failing tests documenting all the issues
- Tests check source code for hardcoded values
- Integration test verifies model should accept new parameters
- Performance baseline test (currently skipped)

## What I Do Next

🔧 **Implementation Plan**:
1. Add `score_thresh`, `nms_thresh`, `detections_per_img` parameters to model constructors
2. Replace hardcoded `0.05` with configurable `score_thresh` parameter
3. Replace hardcoded `0.7` NMS threshold with `nms_thresh` parameter
4. Add NMS to final detection postprocessing
5. Optionally: Switch to GPU-accelerated `torchvisionlib::ops_nms`
6. Update all 4 RCNN model variants consistently

All tests should pass once implementation is complete.

---

**Status**: WIP - Tests implemented, fixes in progress
**Affected Models**: 
- `model_fasterrcnn_resnet50_fpn()`
- `model_fasterrcnn_resnet50_fpn_v2()` 
- `model_fasterrcnn_mobilenet_v3_large_fpn()`
- `model_fasterrcnn_mobilenet_v3_large_320_fpn()`

## I ran this test case locally result below :=> 

Screenshot From 2025-12-11 22-17-47

### CODE REVIEW

File: tests/testthat/test-rcnn-performance.R [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+  result <- tryCatch({
+    model <- torchvision::model_fasterrcnn_resnet50_fpn(
+      pretrained = FALSE,
+      num_classes = 91,
+      score_thresh = 0.5
+    )
+    TRUE
+  }, error = function(e) FALSE)
+  
+  expect_true(result)
```
Comment (cregouby) [inline tests/testthat/test-rcnn-performance.R]: **improvement** **readability** **blocking**: We use the {testthat} function `expect_error()` or the local helper function `expect_no_error()` for that. Please switch to those functions. (applies multiple times)

**Review by cregouby — CHANGES_REQUESTED** [review]
**praise** Thanks for this update. This is much better. 
**todo**: see inline comments
